package sampler

import (
	"context"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"traceiq/internal/model"
)

// AssemblyConfig carries F02 §4.2's `sampler.assembly.*` config keys
// (DR-9). Package-local rather than internal/config.Config per this
// package's DR-2 import ban and this pass's TDD scope.
type AssemblyConfig struct {
	IdleTimeout time.Duration // default 8s
	HardTimeout time.Duration // default 30s
	WheelTick   time.Duration // default 250ms

	// DEVIATION (w9-sampler): max_open_traces_per_shard and
	// memory_high_watermark_bytes (the global 512 MiB byte budget) are not
	// enforced in this pass — early-finalization-under-memory-pressure
	// (F02 §5's first failure mode row) is a follow-up. Tick only finalizes
	// on idle/hard timeout.
}

func DefaultAssemblyConfig() AssemblyConfig {
	return AssemblyConfig{
		IdleTimeout: 8 * time.Second,
		HardTimeout: 30 * time.Second,
		WheelTick:   250 * time.Millisecond,
	}
}

// shardBuf is one assembly shard's open-trace buffer.
//
// w17 final-review fix (BLOCKER, tenant isolation): traces used to be keyed
// by model.TraceID alone. TraceIDs are generated by the *instrumented client*
// and arrive verbatim over OTLP, so they are attacker-chosen and carry no
// cross-tenant uniqueness guarantee at all. Under TraceID-only keying, a span
// from tenant B whose TraceID matched an in-flight trace of tenant A was
// appended to A's buffer; finalize() then evaluated the sampling policy with
// A's Tenant and emitted a Decision/model.Trace under A, so B's span bodies
// were persisted into, and readable from, tenant A's store. Keying on
// TraceKey{Tenant, TraceID} makes the two buffers distinct, which is DR-5's
// requirement that tenancy be part of every scoped lookup rather than an
// attribute carried alongside it. Sharding still hashes the TraceID only, so
// all spans of one trace still land on one shard (DR-10).
type shardBuf struct {
	mu     sync.Mutex
	traces map[TraceKey]*Trace
}

// Manager owns the shard set, assembly buffers, RED extraction, WAL and the
// policy/predicate/baseline collaborators, and is what backs the concrete
// Sampler (impl.go). It is exported so tests can drive Tick/DrainRED
// directly without a live Run() goroutine, keeping finalize timing
// deterministic (DR-31: tests inject model.Clock, not wall time).
type Manager struct {
	cfg      AssemblyConfig
	clock    model.Clock
	wal      WAL
	red      *redAccumulator
	policy   PolicyEvaluator
	governor Governor
	preds    PredicateSet

	ringMu sync.RWMutex
	ring   Ring

	shardsMu sync.RWMutex
	shards   []*shardBuf

	baselinesMu sync.RWMutex
	baselines   map[model.TenantID]BaselineSnapshot

	decisions chan Decision
	tracesCh  chan model.Trace
	redOut    chan model.REDSample

	tracesLostTotal     int64
	rebalanceSplits     int64
	redSamplesDropped   int64
	shardEpoch          uint64
	duplicateSpansTotal int64 // traceiq_ingest_spans_duplicate_total stand-in (FR-F02-5(c))
}

// DuplicateSpansTotal returns the running count of spans dropped as
// duplicate SpanID deliveries (traceiq_ingest_spans_duplicate_total
// stand-in, FR-F02-5(c)).
func (m *Manager) DuplicateSpansTotal() int64 {
	return atomic.LoadInt64(&m.duplicateSpansTotal)
}

// NewManager constructs a Manager with nShards shards, all owned by a
// single MemberID (single-process default; ring resize tests build their
// own Ring directly against ShardFor instead of going through Manager).
func NewManager(cfg AssemblyConfig, clock model.Clock, wal WAL, policy PolicyEvaluator, governor Governor, preds PredicateSet, nShards int) *Manager {
	if nShards < 1 {
		nShards = 1
	}
	members := make([]MemberID, nShards)
	for i := range members {
		members[i] = MemberID(itoa(i))
	}
	shards := make([]*shardBuf, nShards)
	for i := range shards {
		shards[i] = &shardBuf{traces: make(map[TraceKey]*Trace)}
	}
	return &Manager{
		cfg:       cfg,
		clock:     clock,
		wal:       wal,
		red:       newREDAccumulator(),
		policy:    policy,
		governor:  governor,
		preds:     preds,
		ring:      Ring{Epoch: 1, Members: members, State: RingStable},
		shards:    shards,
		baselines: make(map[model.TenantID]BaselineSnapshot),
		decisions: make(chan Decision, 512),
		tracesCh:  make(chan model.Trace, 512),
		redOut:    make(chan model.REDSample, 8192),
	}
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	neg := i < 0
	if neg {
		i = -i
	}
	var buf [20]byte
	pos := len(buf)
	for i > 0 {
		pos--
		buf[pos] = byte('0' + i%10)
		i /= 10
	}
	if neg {
		pos--
		buf[pos] = '-'
	}
	return string(buf[pos:])
}

func (m *Manager) SetBaselineSnapshot(tid model.TenantID, snap BaselineSnapshot) {
	m.baselinesMu.Lock()
	defer m.baselinesMu.Unlock()
	m.baselines[tid] = snap
}

func (m *Manager) baselineFor(tid model.TenantID, service, operation string) KeyBaseline {
	m.baselinesMu.RLock()
	defer m.baselinesMu.RUnlock()
	snap, ok := m.baselines[tid]
	if !ok {
		return KeyBaseline{}
	}
	kb, ok := snap.ByKey[ServiceOp{Service: service, Operation: operation}]
	if !ok {
		return KeyBaseline{}
	}
	return kb
}

func (m *Manager) shardFor(id model.TraceID) int {
	m.ringMu.RLock()
	r := m.ring
	m.ringMu.RUnlock()
	return ShardFor(r, id)
}

// SetRing swaps the routing ring (DR-8 resize). Full drain-then-move
// mid-resize semantics (already-open traces staying with their epoch-e
// owner) are NOT implemented in this pass — this is a hard cutover. Tests
// exercising the drain protocol exercise ShardFor directly instead (see
// ring_test.go); this is flagged as a remaining gap in w9-sampler.md.
func (m *Manager) SetRing(r Ring) {
	m.ringMu.Lock()
	m.ring = r
	m.ringMu.Unlock()
	atomic.AddUint64(&m.shardEpoch, 1)
}

// Consume implements ingest.SpanSink structurally (DR-2): buffers every
// span, RED-extracting it before any shard/assembly decision (DR-9,
// FR-F02-5) regardless of what happens to the span afterward — except a
// duplicate SpanID delivery, which FR-F02-5(c) requires be dropped before
// BOTH assembly and RED.
func (m *Manager) Consume(ctx context.Context, tid model.TenantID, spans []model.Span) error {
	now := m.clock.Now()
	for i := range spans {
		s := &spans[i]
		// The batch's tid is authoritative, not the span's own Tenant field.
		// ingest stamps every span with the resolved tenant before any sink
		// sees it, so in the real pipeline these always agree; overwriting
		// unconditionally (rather than only filling a blank, as before) means a
		// span that somehow arrives pre-stamped with a DIFFERENT tenant cannot
		// end up buffered under tid while claiming to belong to another tenant.
		s.Tenant = tid

		shardIdx := m.shardFor(s.TraceID)
		sb := m.shards[shardIdx%len(m.shards)]
		key := TraceKey{Tenant: tid, TraceID: s.TraceID}

		sb.mu.Lock()
		tr, ok := sb.traces[key]
		if !ok {
			tr = &Trace{
				TraceID:     s.TraceID,
				Tenant:      tid,
				FirstSeen:   now,
				ShardEpoch:  atomic.LoadUint64(&m.shardEpoch),
				seenSpanIDs: make(map[model.SpanID]struct{}),
			}
			sb.traces[key] = tr
		}
		if _, dup := tr.seenSpanIDs[s.SpanID]; dup {
			// FR-F02-5(c): dropped before both assembly and RED, counted in
			// traceiq_ingest_spans_duplicate_total.
			sb.mu.Unlock()
			atomic.AddInt64(&m.duplicateSpansTotal, 1)
			continue
		}
		tr.seenSpanIDs[s.SpanID] = struct{}{}
		tr.Spans = append(tr.Spans, *s)
		tr.LastSeen = now
		tr.ByteSize += int(s.SizeBytes)
		sb.mu.Unlock()

		// RED extraction happens only for a span that survived the
		// duplicate check — still "before every discard" for every OTHER
		// reason a span's body might later be dropped (shard_full,
		// max_spans_per_trace truncation), per DR-9's three holes; a
		// duplicate is the one case DR-9 itself excludes from RED.
		m.red.Accumulate(now, tid, s)

		if m.wal != nil {
			_ = m.wal.Append(shardIdx, key, *s)
		}
	}
	return nil
}

// Tick performs one finalize sweep: any buffer past IdleTimeout (since
// LastSeen) or HardTimeout (since FirstSeen) is finalized. Exposed
// directly (rather than only via a background goroutine) so tests can
// drive finalize deterministically off a fake clock (DR-31).
func (m *Manager) Tick(ctx context.Context) {
	now := m.clock.Now()
	m.shardsMu.RLock()
	shards := m.shards
	m.shardsMu.RUnlock()

	for shardIdx, sb := range shards {
		var due []*Trace
		sb.mu.Lock()
		for key, tr := range sb.traces {
			if now.Sub(tr.LastSeen) >= m.cfg.IdleTimeout || now.Sub(tr.FirstSeen) >= m.cfg.HardTimeout {
				due = append(due, tr)
				delete(sb.traces, key)
			}
		}
		sb.mu.Unlock()

		for _, tr := range due {
			m.finalize(ctx, shardIdx, tr, false)
		}
	}
}

// finalize converts a shard-local Trace buffer into model.Trace, evaluates
// the keep policy (unless forced, e.g. FlushAll's KeepShed), and emits on
// Decisions()/Traces().
func (m *Manager) finalize(ctx context.Context, shardIdx int, tr *Trace, forceShed bool) {
	mt := toModelTrace(tr)

	var decision Decision
	if forceShed {
		decision = Decision{
			Tenant: tr.Tenant, TraceID: tr.TraceID, Keep: false,
			Reason: model.KeepShed, DecidedAt: m.clock.Now(),
		}
	} else {
		kb := m.baselineFor(tr.Tenant, mt.RootService, mt.RootOperation)
		predMatch := m.preds.Match(&mt)
		decision = m.policy.Evaluate(ctx, tr.Tenant, &mt, kb, predMatch, m.governor)
	}

	if m.wal != nil {
		_ = m.wal.Truncate(shardIdx, TraceKey{Tenant: tr.Tenant, TraceID: tr.TraceID})
	}

	m.decisions <- decision
	if decision.Keep {
		m.tracesCh <- mt
	}
}

func toModelTrace(tr *Trace) model.Trace {
	svcSet := map[string]struct{}{}
	errCount := 0
	for i := range tr.Spans {
		svcSet[spanService(&tr.Spans[i])] = struct{}{}
		if spanIsError(&tr.Spans[i]) {
			errCount++
		}
	}
	services := make([]string, 0, len(svcSet))
	for s := range svcSet {
		if s != "" {
			services = append(services, s)
		}
	}
	sort.Strings(services)

	var rootSpanID model.SpanID
	rootService, rootOp := "", ""
	for i := range tr.Spans {
		if spanIsRoot(&tr.Spans[i]) {
			rootSpanID = tr.Spans[i].SpanID
			rootService = spanService(&tr.Spans[i])
			rootOp = tr.Spans[i].Name
			break
		}
	}
	if rootService == "" && len(tr.Spans) > 0 {
		rootService = spanService(&tr.Spans[0])
		rootOp = tr.Spans[0].Name
	}

	durNanos := traceMaxDurationNanos(tr.Spans)

	return model.Trace{
		TraceID:       tr.TraceID,
		Tenant:        tr.Tenant,
		Spans:         tr.Spans,
		RootSpanID:    rootSpanID,
		RootService:   rootService,
		RootOperation: rootOp,
		StartUnixNano: uint64(tr.FirstSeen.UnixNano()),
		EndUnixNano:   uint64(tr.LastSeen.UnixNano()),
		DurationNanos: durNanos,
		SpanCount:     len(tr.Spans),
		ErrorCount:    errCount,
		Services:      services,
		PathSignature: computePathSignature(tr.Spans),
		Complete:      !tr.Truncated,
		Truncated:     tr.Truncated,
		SizeBytes:     uint64(tr.ByteSize),
		AssembledAt:   uint64(tr.LastSeen.UnixNano()),
	}
}

// FlushAll implements FR-F02-9: force-completes every open trace with
// KeepReason = KeepShed, emits its decision (and, via the RED accumulator,
// its RED — already extracted continuously at Consume time), then
// truncates the WAL.
func (m *Manager) FlushAll(ctx context.Context) error {
	m.shardsMu.RLock()
	shards := m.shards
	m.shardsMu.RUnlock()

	for shardIdx, sb := range shards {
		sb.mu.Lock()
		due := make([]*Trace, 0, len(sb.traces))
		for key, tr := range sb.traces {
			due = append(due, tr)
			delete(sb.traces, key)
		}
		sb.mu.Unlock()
		for _, tr := range due {
			m.finalize(ctx, shardIdx, tr, true)
		}
	}
	return nil
}

// ReplayWAL implements FR-F02-9: re-assembles every undecided trace from
// the WAL before receivers bind.
//
// DEVIATION (w9-sampler): with MemWAL (wal.go's deviation note) there is no
// real crash to recover from within one process's lifetime, so this mainly
// exists to prove the reassembly path compiles and round-trips; a
// kill-and-restart integration test against a disk-backed WAL
// implementation (AC-F02-11) is a follow-up.
func (m *Manager) ReplayWAL(ctx context.Context) (ReplayReport, error) {
	start := m.clock.Now()
	report := ReplayReport{}
	m.shardsMu.RLock()
	nShards := len(m.shards)
	m.shardsMu.RUnlock()

	for shardIdx := 0; shardIdx < nShards; shardIdx++ {
		byTrace, err := m.wal.Replay(shardIdx)
		if err != nil {
			return report, err
		}
		if len(byTrace) == 0 {
			continue
		}
		report.SegmentsReplayed++
		sb := m.shards[shardIdx]
		sb.mu.Lock()
		for key, spans := range byTrace {
			tr, ok := sb.traces[key]
			if !ok {
				// w17 final-review fix: the replayed Trace used to be built as
				// &Trace{TraceID: tid, ...} with Tenant left at its zero value,
				// so every trace recovered from the WAL was finalized under
				// TenantID("") — its Decision, its policy evaluation and its
				// persisted body all lost the tenant they were journalled for.
				// TraceKey now carries the tenant through replay.
				tr = &Trace{
					TraceID:     key.TraceID,
					Tenant:      key.Tenant,
					FirstSeen:   m.clock.Now(),
					seenSpanIDs: make(map[model.SpanID]struct{}),
				}
				sb.traces[key] = tr
			}
			if tr.seenSpanIDs == nil {
				// Defensive: a Trace reachable here always comes either from
				// this constructor (map set) or from Consume (map set) — nil
				// only if some future caller starts building *Trace directly.
				tr.seenSpanIDs = make(map[model.SpanID]struct{})
			}
			for _, s := range spans {
				if _, dup := tr.seenSpanIDs[s.SpanID]; dup {
					continue
				}
				tr.seenSpanIDs[s.SpanID] = struct{}{}
				tr.Spans = append(tr.Spans, s)
			}
			tr.LastSeen = m.clock.Now()
			report.TracesReplayed++
		}
		sb.mu.Unlock()
	}
	report.TracesLost = atomic.LoadInt64(&m.tracesLostTotal)
	report.Duration = m.clock.Since(start)
	return report, nil
}

// DrainRED flushes the RED accumulator and forwards every sample onto
// REDSamples() with drop-oldest-plus-counter semantics (cap 8192,
// FR-F02-8). Call periodically from Run(), or directly from tests/FlushAll
// to make emission deterministic instead of racing a background ticker.
func (m *Manager) DrainRED() {
	for _, s := range m.red.Flush() {
		select {
		case m.redOut <- s:
		default:
			// drop-oldest: make room, then insert.
			select {
			case <-m.redOut:
			default:
			}
			atomic.AddInt64(&m.redSamplesDropped, 1)
			select {
			case m.redOut <- s:
			default:
			}
		}
	}
}

// Run drives Tick and DrainRED off cfg.WheelTick until ctx is done.
// Production wiring only; tests call Tick/DrainRED directly for
// determinism (DR-31).
func (m *Manager) Run(ctx context.Context) {
	ticker := m.clock.NewTicker(m.cfg.WheelTick)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C():
			m.Tick(ctx)
			m.DrainRED()
		}
	}
}

func (m *Manager) Decisions() <-chan Decision         { return m.decisions }
func (m *Manager) Traces() <-chan model.Trace         { return m.tracesCh }
func (m *Manager) REDSamples() <-chan model.REDSample { return m.redOut }

func (m *Manager) Stats() Stats {
	m.shardsMu.RLock()
	defer m.shardsMu.RUnlock()
	st := Stats{
		RingEpoch:       atomic.LoadUint64(&m.shardEpoch),
		TracesLostTotal: atomic.LoadInt64(&m.tracesLostTotal),
		RebalanceSplits: atomic.LoadInt64(&m.rebalanceSplits),
	}
	for i, sb := range m.shards {
		sb.mu.Lock()
		open := len(sb.traces)
		var bytes int64
		for _, tr := range sb.traces {
			bytes += int64(tr.ByteSize)
		}
		sb.mu.Unlock()
		st.OpenTraces += int64(open)
		st.BytesInFlight += bytes
		st.Shards = append(st.Shards, ShardStats{ShardID: i, OpenTraces: open, BytesInFlight: bytes})
	}
	return st
}
