package config

import "time"

// Default returns the dev-profile default Config (01 §7's YAML block,
// FR-XOPS-1's zero-external-dependency dev start: loopback listeners,
// auth.mode: token, tenancy disabled, sqlite/parquet_local drivers,
// cluster.bus.driver: none, rca.reasoner: auto (-> rules without a key)).
// Load starts from this value, then overlays traceiq.yaml (if present) and
// TRACEIQ_ environment overrides on top of it (01 §7's precedence chain).
func Default() *Config {
	return &Config{
		Server: ServerConfig{
			Mode:          "single",
			Profile:       "dev",
			NodeID:        "",
			DataDir:       "./traceiq-data",
			LogLevel:      "info",
			LogFormat:     "json",
			ShutdownGrace: 45 * time.Second,
		},
		Tenancy: TenancyConfig{
			Enabled:       false,
			DefaultTenant: "default",
		},
		Ingest: IngestConfig{
			OTLPGRPC: IngestReceiverConfig{
				Enabled:  true,
				Endpoint: "127.0.0.1:4317",
				TLS:      TLSConfig{Enabled: true, MinVersion: "1.3"},
			},
			OTLPHTTP: IngestReceiverConfig{
				Enabled:  true,
				Endpoint: "127.0.0.1:4318",
				TLS:      TLSConfig{Enabled: true, MinVersion: "1.3"},
			},
			JaegerGRPC: IngestReceiverConfig{Enabled: false, TLS: TLSConfig{Enabled: true, MinVersion: "1.3"}},
			ZipkinHTTP: IngestReceiverConfig{Enabled: false, TLS: TLSConfig{Enabled: true, MinVersion: "1.3"}},
			Auth: IngestAuthConfig{
				Mode:       "token",
				TokensFile: "${data_dir}/ingest_tokens.json",
			},
			DecodeWorkers: 0,
			Queue: IngestQueueConfig{
				Capacity:       1024,
				MaxBytes:       268435456,
				EnqueueTimeout: 100 * time.Millisecond,
				OverflowPolicy: "shed",
			},
			Limits: IngestLimitsConfig{
				MaxSpanBytes:           524288,
				MaxAttributesPerSpan:   128,
				MaxAttributeValueBytes: 4096,
				OversizeAttr:           "truncate",
				MaxAttributeKeyBytes:   256,
				MaxEventsPerSpan:       128,
				MaxLinksPerSpan:        128,
				MaxSpansPerBatch:       10000,
				MaxSpansPerTrace:       10000,
				MaxRequestBytes:        4194304,
				PerTenantBytesPerSec:   20971520,
				ClockSkewFuture:        5 * time.Minute,
				MaxSpanAge:             24 * time.Hour,
			},
		},
		Sampler: SamplerConfig{
			Shards:         0,
			ShardQueueSize: 4096,
			Assembly: SamplerAssemblyConfig{
				IdleTimeout:              8 * time.Second,
				HardTimeout:              30 * time.Second,
				MaxOpenTracesPerShard:    50000,
				MemoryHighWatermarkBytes: 536870912,
				WheelTick:                250 * time.Millisecond,
			},
			WAL: SamplerWALConfig{
				Enabled:         true,
				Dir:             "${data_dir}/sampler/wal",
				FlushInterval:   time.Second,
				MaxSegmentBytes: 67108864,
			},
			Policy: SamplerPolicyConfig{
				KeepErrors:                  true,
				SlowQuantile:                0.99,
				SlowMinDuration:             250 * time.Millisecond,
				RarePathLookbackDays:        7,
				RarePathKeepsPerMin:         60,
				MaxPathSignatureCardinality: 200000,
				BaselineMinSamples:          200,
				HealthySampleRate:           0.01,
				FloorTracesPerMinPerService: 6,
				MaxKeepRate:                 0.25,
			},
			Baseline: SamplerBaselineConfig{RefreshInterval: 60 * time.Second},
			Interest: SamplerInterestConfig{
				Enabled:                 true,
				MaxPredicates:           32,
				MaxRecurrencePredicates: 8,
				MaxTraceIDsPerPredicate: 1024,
				ScopeTTL:                30 * time.Minute,
				RecurrenceTTL:           24 * time.Hour,
				NarrowAtKeepRate:        0.25,
				Persist:                 true,
			},
			Red: SamplerRedConfig{DedupeWindow: 200000},
		},
		Store: StoreConfig{
			Hot: StoreHotConfig{
				Driver: "sqlite",
				IndexedAttributeKeys: []string{
					"http.response.status_code",
					"http.route",
					"error.type",
					"rpc.method",
					"db.system.name",
					"peer.service",
					"k8s.pod.name",
					"service.version",
				},
				IndexAttrsForKinds:       []int{2, 5},
				MaxIndexedAttrValueBytes: 128,
				MaxPathSignatures:        200000,
				MaxKeptSpansPerSec:       1200,
				SQLite: StoreHotSQLiteConfig{
					Path:               "${data_dir}/hot/traceiq.db",
					BusyTimeout:        5 * time.Second,
					CacheSizeKB:        262144,
					MaxReadConns:       8,
					BatchTraces:        200,
					BatchInterval:      250 * time.Millisecond,
					CheckpointInterval: 60 * time.Second,
					WALAutocheckpoint:  4000,
				},
				ClickHouse: StoreHotClickHouseConfig{Database: "traceiq", MaxOpenConns: 16},
			},
			Cold: StoreColdConfig{
				Driver: "parquet_local",
				Parquet: StoreColdParquetConfig{
					Path:             "${data_dir}/cold",
					Compression:      "zstd",
					CompressionLevel: 3,
					RowGroupBytes:    33554432,
					TargetBlockBytes: 134217728,
					FlushInterval:    5 * time.Minute,
					MaxOpenBlocks:    2,
					WALDir:           "${data_dir}/cold/wal",
					WALFsyncInterval: 250 * time.Millisecond,
					WALFsyncBytes:    4194304,
					WALRetain:        10 * time.Minute,
				},
				Compaction: StoreColdCompactionConfig{
					TombstoneRatio:  0.02,
					MaxTombstoneAge: 24 * time.Hour,
					OrphanGrace:     2 * time.Hour,
					ReaperInterval:  15 * time.Minute,
				},
			},
			Retention: StoreRetentionConfig{
				HotSpanRows:        24 * time.Hour,
				HotTraceRows:       7 * 24 * time.Hour,
				HotRollups:         30 * 24 * time.Hour,
				ColdAnomalous:      30 * 24 * time.Hour,
				ColdSampled:        7 * 24 * time.Hour,
				Red10s:             48 * time.Hour,
				Red5m:              14 * 24 * time.Hour,
				RedRollups:         400 * 24 * time.Hour,
				Topology10s:        6 * time.Hour,
				Topology5m:         7 * 24 * time.Hour,
				Topology1h:         30 * 24 * time.Hour,
				Investigations:     400 * 24 * time.Hour,
				Audit:              2555 * 24 * time.Hour,
				CompactionInterval: time.Hour,
			},
			Budget: StoreBudgetConfig{
				MaxDiskBytes:  26843545600,
				HighWatermark: 0.85,
				ActionOnFull:  "shed_sampled",
			},
			Cost: StoreCostConfig{
				SignalInterval:   60 * time.Second,
				MeasureWindow:    5 * time.Minute,
				Deadband:         0.15,
				MaxStep:          0.5,
				RecoveryRamp:     1.25,
				AdaptiveFloorMin: 0.0001,
				AdaptiveFloorMax: 1.0,
				SettlingTarget:   30 * time.Minute,
			},
		},
		Topology: TopologyConfig{
			Bucket:               10 * time.Second,
			Window:               15 * time.Minute,
			MaxEdges:             20000,
			MaxOperationsPerEdge: 20,
			NewEdgeMinCalls:      5,
			VanishedAfter:        30 * time.Minute,
		},
		Anomaly: AnomalyConfig{
			Detectors:     []string{"latency_shift", "error_burst", "new_error_signature", "throughput_drop", "topology_change"},
			EvalInterval:  30 * time.Second,
			EvalWindow:    90 * time.Second,
			DebounceTicks: 2,
			Baseline: AnomalyBaselineConfig{
				Estimator:              "p2",
				TDigestCompression:     100,
				EWMAAlpha:              0.2,
				Seasonal:               true,
				SeasonSlots:            31,
				WarmupSamples:          200,
				WarmupSamplesPerBucket: 30,
				ColdStartMultiplier:    1.5,
				MaxColdStart:           24 * time.Hour,
				MaxKeys:                10000,
				MaxKeysGlobal:          20000,
				MaxErrorSignatures:     20000,
				CheckpointInterval:     60 * time.Second,
				CheckpointMaxRows:      2000,
				MinRPS:                 0.1,
			},
			Thresholds: AnomalyThresholdsConfig{
				LatencyRatio:              1.5,
				LatencyAbsDelta:           50 * time.Millisecond,
				ErrorRateDelta:            0.05,
				ErrorBurstRatio:           3.0,
				ThroughputDropRatio:       0.5,
				NewErrorSignatureLookback: 7 * 24 * time.Hour,
				NewErrorSigMinCalls:       5,
				MinCalls:                  20,
				MinEventScore:             0.55,
			},
			Grouping: AnomalyGroupingConfig{
				Window:               5 * time.Minute,
				TopologyHops:         2,
				MaxEventsPerIncident: 200,
				MaxOpenIncidents:     200,
				DedupeTTL:            30 * time.Minute,
				NeighborCacheEntries: 4096,
				NeighborCacheTTL:     60 * time.Second,
			},
			DeployMarkers: AnomalyDeployMarkersConfig{
				Enabled:           true,
				CorrelationWindow: 30 * time.Minute,
				Settle:            2 * time.Minute,
			},
		},
		RCA: RCAConfig{
			Enabled:                     true,
			AutoInvestigate:             true,
			MinIncidentScore:            0.6,
			MaxConcurrentInvestigations: 2,
			Reasoner:                    "auto",
			ConfidenceThreshold:         0.75,
			Budget: RCABudgetConfig{
				WallClock:                      5 * time.Minute,
				MaxStepWallClock:               45 * time.Second,
				MaxSteps:                       24,
				MaxToolCalls:                   40,
				MaxTokensIn:                    120000,
				MaxCachedTokensIn:              600000,
				MaxTokensOut:                   64000,
				MaxCostMicroUSD:                500000,
				MaxCostMicroUSDPerTenantPerDay: 20000000,
				MaxCostMicroUSDGlobalPerDay:    100000000,
				MaxRowsPerToolCall:             500,
				MaxEvidenceBytes:               8192,
				VerbatimDigestWindow:           3,
				CompactedVerdictTokens:         60,
			},
			Tools: RCAToolsConfig{MaxWindow: 6 * time.Hour},
			LLM: RCALLMConfig{
				Provider:        "anthropic",
				BaseURL:         "https://api.anthropic.com",
				Model:           "claude-opus-5",
				Effort:          "medium",
				Thinking:        "adaptive",
				APIKeyEnv:       "TRACEIQ_ANTHROPIC_API_KEY",
				Timeout:         25 * time.Second,
				MaxRetries:      2,
				MaxOutputTokens: 1600,
				PromptCache:     true,
			},
		},
		Correlate: CorrelateConfig{
			Logs: CorrelateBackendConfig{
				Driver:     "file",
				Path:       "${data_dir}/devlogs",
				Timeout:    10 * time.Second,
				MaxLines:   200,
				TenantMode: "none",
			},
			Metrics: CorrelateBackendConfig{
				Driver:     "file",
				Path:       "${data_dir}/devmetrics",
				Timeout:    10 * time.Second,
				Step:       30 * time.Second,
				TenantMode: "none",
			},
			AllowPrivateNetworks: false,
			MaxInflight:          4,
			MaxInflightGlobal:    16,
			BreakerFailures:      5,
			BreakerOpen:          30 * time.Second,
			Cache: CorrelateCacheConfig{
				Enabled:    true,
				MaxEntries: 2048,
				TTL:        60 * time.Second,
			},
		},
		Memory: MemoryConfig{
			Enabled:    true,
			Embeddings: MemoryEmbeddingsConfig{Driver: "lexical", Dim: 256},
			Retrieval: MemoryRetrievalConfig{
				TopK:                8,
				MinSimilarity:       0.35,
				MaxCandidates:       500,
				Hybrid:              false,
				WeightDecayHalfLife: 90 * 24 * time.Hour,
			},
			Index: MemoryIndexConfig{MaxVocabulary: 50000},
			Consolidation: MemoryConsolidationConfig{
				Interval:            24 * time.Hour,
				HourOfDay:           3,
				PruneAfterDays:      400,
				DedupeThreshold:     0.6,
				MinhashPermutations: 128,
				MinhashBands:        32,
				MaxDuration:         15 * time.Minute,
			},
		},
		Remediate: RemediateConfig{
			Enabled:                       false,
			Mode:                          "dryrun",
			Executor:                      "dryrun",
			RequireApproval:               true,
			ApproverRoles:                 []string{"approver", "admin"},
			AutoExecuteOnApprove:          false,
			ActionBudgetPerIncident:       2,
			MaxBudgetOverridesPerIncident: 1,
			ApprovalTTL:                   15 * time.Minute,
			ProposalTTL:                   60 * time.Minute,
			VerifyWindow:                  10 * time.Minute,
			AutoRollback:                  true,
			ExecTimeout:                   30 * time.Second,
			SnapshotDir:                   "${data_dir}/snapshots",
		},
		Alerting: AlertingConfig{
			Gate:          "investigation",
			MaxWaitForRCA: 5 * time.Minute,
			MinSeverity:   "P2",
			Deadman: AlertingDeadmanConfig{
				Enabled:  true,
				Interval: 10 * time.Minute,
			},
		},
		NL: NLConfig{
			Enabled:             true,
			Interpreter:         "auto",
			ContextTurns:        5,
			MaxQuestionBytes:    4096,
			AnswerEvidenceLimit: 20,
		},
		API: APIConfig{
			Endpoint:       "127.0.0.1:8443",
			UI:             true,
			MCP:            true,
			MCPPath:        "/v1/mcp",
			ReadTimeout:    30 * time.Second,
			WriteTimeout:   30 * time.Second,
			IdleTimeout:    120 * time.Second,
			MaxBodyBytes:   1048576,
			RateLimitRPS:   100,
			RateLimitBurst: 200,
		},
		Auth: AuthConfig{
			Mode:                   "token",
			BootstrapAdminTokenEnv: "TRACEIQ_BOOTSTRAP_ADMIN_TOKEN",
			TokenHash:              "argon2id",
			TLS:                    TLSConfig{Enabled: true, MinVersion: "1.3"},
			Audit: AuthAuditConfig{
				Enabled:        true,
				HashChain:      true,
				AnchorInterval: 5 * time.Minute,
				AnchorSink:     "file",
				AnchorDir:      "${data_dir}/audit/anchors",
				RetentionDays:  2555,
			},
			RateLimit: AuthRateLimitConfig{MaxKeys: 65536},
		},
		Eval: EvalConfig{
			Enabled:      false,
			ScenariosDir: "eval/scenarios",
			OutputDir:    "${data_dir}/eval",
			Mode:         "offline",
			Parallelism:  4,
			Isolation:    "process",
			Reasoner:     "rules",
		},
		SelfObs: SelfObsConfig{
			MetricsEndpoint: "127.0.0.1:9464",
			HealthPath:      "/healthz",
			ReadyPath:       "/readyz",
		},
		Cluster: ClusterConfig{
			Bus: ClusterBusConfig{Driver: "none", Partitions: 32},
		},
		Ops: OpsConfig{
			ShutdownGrace: 45 * time.Second,
			Backup: OpsBackupConfig{
				Enabled:           false,
				Dir:               "${data_dir}/backup",
				ControlInterval:   5 * time.Minute,
				TelemetryInterval: 6 * time.Hour,
				ColdWALShip:       true,
				Retain:            7 * 24 * time.Hour,
				VerifyOnWrite:     true,
			},
		},
	}
}
